var vector;
var vector2;
vector = [2, 5];
vector2 = [5, 10];
var vector_resultante = [vector[0] + vector2[0], vector[1] + vector2[1]];
console.log(vector_resultante);
var tupla_5_elementos = [1, 2, 3, 4, 5];
var tupla_profesor = ["Christian", 1.74];
var tupla_estudiante = ['Juan', 1.58];
console.log(tupla_estudiante[0] + " mide " + tupla_estudiante[1] + " mts");
